M48
; DRILL file {KiCad 7.0.11-2.fc39} date Fri 07 Jun 2024 09:19:11 AM EDT
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-06-07T09:19:11-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11-2.fc39
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0827
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1378
%
G90
G05
T1
X5.575Y-3.845
X5.58Y-2.705
T2
X5.26Y-2.63
X5.93Y-2.63
M30
